// <auto-generated />
using GDLevels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GDLevels.Migrations
{
    [DbContext(typeof(GDLevelsDataContext))]
    [Migration("20220123200705_IsUnique_to_AlternateKey")]
    partial class IsUnique_to_AlternateKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("GDLevels.Models.Level", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequestTime")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasAlternateKey("LevelID");

                    b.ToTable("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
