// <auto-generated />
using GDLevels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GDLevels.Migrations
{
    [DbContext(typeof(GDLevelsDataContext))]
    partial class GDLevelsDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("GDLevels.Models.Level", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LevelID")
                        .IsUnique();

                    b.ToTable("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
